schema_version: 1

context:
  version: "2026.1"

package:
  name: staticcheck
  version: ${{ version }}

source:
  url: https://github.com/dominikh/go-tools/archive/${{ version }}.tar.gz
  sha256: 4b20d65194e5462264c784f2968de65fcd7aba8e9efa37aa9b1fadc13b29699b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - staticcheck --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: State of the art linter for the Go programming language
  homepage: https://staticcheck.io/
  repository: https://github.com/dominikh/go-tools

extra:
  recipe-maintainers:
    - danielnachun
