schema_version: 1

context:
  version: "2026.2.1"

package:
  name: staticcheck
  version: ${{ version }}

source:
  url: https://github.com/dominikh/go-tools/archive/${{ version }}.tar.gz
  sha256: 8d807cd909f4481d6777f7707e5ae75dcc399e14d68ff14a3c814731826e0dfc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - staticcheck --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: State of the art linter for the Go programming language
  homepage: https://staticcheck.io/
  repository: https://github.com/dominikh/go-tools

extra:
  recipe-maintainers:
    - danielnachun
