schema_version: 1

context:
  version: "2026.2"

package:
  name: staticcheck
  version: ${{ version }}

source:
  url: https://github.com/dominikh/go-tools/archive/${{ version }}.tar.gz
  sha256: 72fa00a4bef32ab52aa3ca916e70108ca021ef3c35dda555350c0b670c432033

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - staticcheck --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: State of the art linter for the Go programming language
  homepage: https://staticcheck.io/
  repository: https://github.com/dominikh/go-tools

extra:
  recipe-maintainers:
    - danielnachun
